### ISSUE TITLE
Make codebase adhere to our base JS standards

### ISSUE THREAD

**Issue by AlexCatch** [langleyfoxall/react-dynamic-context-menu#3]
There are a few sections of the project that don't adhere to our base JS standards.

It might be something to get ESLint setup & configured for this.

https://github.com/langleyfoxall/technologies/blob/master/styleguides/javascript/core.md

**Comment by NilesB** [comment]
@AlexCatch PRs are accepted

**Comment by AlexCatch** [comment]
I think if you're making an open source project under the company - you as the project author should make sure it meets the companies internal standards before a v1.0.0 release at the bare minimum.
